# Build a self-contained one-click Windows .exe for Easy-ChatBox Editor.
# Uses the built-in .NET Framework C# compiler (csc.exe) so no extra runtime is required.
# The exe embeds the Vite dist output and serves it from a local HTTP server,
# then opens the default browser.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$dist = Join-Path $root 'dist'
$packDir = Join-Path $root 'pack'
$generated = Join-Path $packDir 'Program.generated.cs'
$exePath = Join-Path $root 'EasyChatBoxEditor.exe'

# 1) Build the web app if dist is missing/stale
if (-not (Test-Path (Join-Path $dist 'index.html'))) {
    Write-Host 'dist not found, running npm run build ...'
    Push-Location $root
    try { npm run build | Out-Host } finally { Pop-Location }
}

# 2) Find csc.exe
$csc = @(
    'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe',
    'C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe'
) | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not $csc) {
    throw 'csc.exe not found. This script requires .NET Framework 4.x on Windows.'
}

# 3) Collect dist files
$files = Get-ChildItem -Path $dist -Recurse -File | Sort-Object FullName
$assetMap = New-Object System.Collections.Generic.List[string]
$resourceArgs = New-Object System.Collections.Generic.List[string]
$i = 0
foreach ($file in $files) {
    $rel = $file.FullName.Substring($dist.Length).TrimStart('\', '/').Replace('\', '/')
    $url = '/' + $rel
    $resName = 'ec_' + $i
    $assetMap.Add("            { `"$url`", `"$resName`" },")
    $resourceArgs.Add("/resource:$($file.FullName),$resName")
    $i++
}

$mapText = $assetMap -join [Environment]::NewLine

$template = @'
// Auto-generated by scripts/build-exe.ps1 -- do not edit manually.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;

public static class Program
{
    private static readonly Dictionary<string, string> AssetMap = new Dictionary<string, string>
    {
__ASSET_MAP__
    };

    private static readonly Dictionary<string, byte[]> AssetCache = new Dictionary<string, byte[]>();
    private static readonly Dictionary<string, string> MimeMap = new Dictionary<string, string>
    {
        { ".html", "text/html; charset=utf-8" },
        { ".js", "application/javascript; charset=utf-8" },
        { ".css", "text/css; charset=utf-8" },
        { ".json", "application/json; charset=utf-8" },
        { ".txt", "text/plain; charset=utf-8" },
        { ".svg", "image/svg+xml" },
        { ".png", "image/png" },
        { ".jpg", "image/jpeg" },
        { ".jpeg", "image/jpeg" },
        { ".gif", "image/gif" },
        { ".ico", "image/x-icon" },
        { ".webp", "image/webp" },
        { ".woff", "font/woff" },
        { ".woff2", "font/woff2" },
        { ".map", "application/json" }
    };

    [STAThread]
    public static void Main()
    {
        PreloadAssets();

        // 使用固定端口，保证浏览器 localStorage 的源（127.0.0.1:端口）跨启动不变，
        // 这样用户手动选择的 register.json 才能被“永久记住”。
        int port = 17890;
        TcpListener listener = null;
        try
        {
            listener = new TcpListener(IPAddress.Loopback, port);
            listener.Start();
        }
        catch
        {
            port = 0;
            listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
        }
        port = ((IPEndPoint)listener.LocalEndpoint).Port;
        string url = "http://127.0.0.1:" + port + "/";

        Thread acceptThread = new Thread(delegate ()
        {
            while (true)
            {
                try
                {
                    TcpClient client = listener.AcceptTcpClient();
                    ThreadPool.QueueUserWorkItem(delegate { HandleClient(client); });
                }
                catch
                {
                    break;
                }
            }
        });
        acceptThread.IsBackground = true;
        acceptThread.Start();

        OpenBrowser(url);

        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        ApplicationContext context = new ApplicationContext();
        NotifyIcon notify = new NotifyIcon();
        notify.Icon = SystemIcons.Application;
        notify.Text = "Easy-ChatBox 编辑器";
        notify.Visible = true;
        ContextMenu menu = new ContextMenu();
        menu.MenuItems.Add("打开编辑器", delegate { OpenBrowser(url); });
        menu.MenuItems.Add("退出", delegate
        {
            notify.Visible = false;
            Application.Exit();
        });
        notify.ContextMenu = menu;

        Application.Run(context);

        notify.Dispose();
        listener.Stop();
    }

    private static void PreloadAssets()
    {
        Assembly asm = Assembly.GetExecutingAssembly();
        foreach (KeyValuePair<string, string> kv in AssetMap)
        {
            if (AssetCache.ContainsKey(kv.Key)) continue;
            using (Stream stream = asm.GetManifestResourceStream(kv.Value))
            {
                if (stream == null) continue;
                using (MemoryStream ms = new MemoryStream())
                {
                    stream.CopyTo(ms);
                    AssetCache[kv.Key] = ms.ToArray();
                }
            }
        }
    }

    private static void OpenBrowser(string url)
    {
        try
        {
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = url;
            psi.UseShellExecute = true;
            Process.Start(psi);
        }
        catch
        {
        }
    }

    private static string GetSettingsPath()
    {
        string dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "EasyChatBoxEditor");
        return Path.Combine(dir, "settings.json");
    }

    private static string ReadSettingsFile()
    {
        try
        {
            if (File.Exists(GetSettingsPath()))
            {
                return File.ReadAllText(GetSettingsPath(), Encoding.UTF8);
            }
        }
        catch
        {
        }
        return "{}";
    }

    private static void WriteSettingsFile(string json)
    {
        try
        {
            string path = GetSettingsPath();
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, json, Encoding.UTF8);
        }
        catch
        {
        }
    }

    private static Dictionary<string, object> ReadSettingsObject()
    {
        try
        {
            string json = ReadSettingsFile();
            return new JavaScriptSerializer().Deserialize<Dictionary<string, object>>(json);
        }
        catch
        {
            return new Dictionary<string, object>();
        }
    }

    private static string JsonEscape(string s)
    {
        if (s == null) return "\"\"";
        StringBuilder sb = new StringBuilder();
        sb.Append('"');
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string OpenRegisterDialog()
    {
        string result = "{}";
        Exception dialogError = null;
        Thread dialogThread = new Thread(delegate ()
        {
            try
            {
                using (OpenFileDialog dialog = new OpenFileDialog())
                {
                    dialog.Title = "选择 register.json";
                    dialog.Filter = "register.json (*.json)|*.json|All files (*.*)|*.*";
                    if (dialog.ShowDialog() == DialogResult.OK)
                    {
                        string text = File.ReadAllText(dialog.FileName, Encoding.UTF8);
                        result = "{\"name\":" + JsonEscape(Path.GetFileName(dialog.FileName)) +
                                 ",\"path\":" + JsonEscape(dialog.FileName) +
                                 ",\"text\":" + JsonEscape(text) + "}";
                    }
                }
            }
            catch (Exception ex)
            {
                dialogError = ex;
            }
        });
        dialogThread.SetApartmentState(ApartmentState.STA);
        dialogThread.Start();
        dialogThread.Join();
        if (dialogError != null) return "{}";
        return result;
    }

    private static string ReloadRegisterFromDisk()
    {
        try
        {
            Dictionary<string, object> settings = ReadSettingsObject();
            if (settings.ContainsKey("register"))
            {
                Dictionary<string, object> reg = settings["register"] as Dictionary<string, object>;
                if (reg != null && reg.ContainsKey("path"))
                {
                    string path = Convert.ToString(reg["path"]);
                    if (!string.IsNullOrEmpty(path) && File.Exists(path))
                    {
                        string text = File.ReadAllText(path, Encoding.UTF8);
                        return "{\"name\":" + JsonEscape(Path.GetFileName(path)) +
                               ",\"path\":" + JsonEscape(path) +
                               ",\"text\":" + JsonEscape(text) + "}";
                    }
                }
            }
        }
        catch
        {
        }
        return ReadSettingsFile();
    }

    private static string SaveFileDialogWithContent(string suggestedName, string content)
    {
        string result = "{}";
        Exception dialogError = null;
        Thread dialogThread = new Thread(delegate ()
        {
            try
            {
                using (SaveFileDialog dialog = new SaveFileDialog())
                {
                    dialog.Title = "保存剧本";
                    dialog.Filter = "Easy-ChatBox 剧本 (*.txt;*.chat)|*.txt;*.chat|文本文件 (*.txt)|*.txt|所有文件 (*.*)|*.*";
                    dialog.FileName = suggestedName ?? "script.txt";
                    if (dialog.ShowDialog() == DialogResult.OK)
                    {
                        File.WriteAllText(dialog.FileName, content ?? "", Encoding.UTF8);
                        result = "{\"name\":" + JsonEscape(Path.GetFileName(dialog.FileName)) +
                                 ",\"path\":" + JsonEscape(dialog.FileName) + "}";
                    }
                }
            }
            catch (Exception ex)
            {
                dialogError = ex;
            }
        });
        dialogThread.SetApartmentState(ApartmentState.STA);
        dialogThread.Start();
        dialogThread.Join();
        if (dialogError != null) return "{}";
        return result;
    }

    private static void HandleClient(TcpClient client)
    {
        try
        {
            using (client)
            using (NetworkStream stream = client.GetStream())
            {
                byte[] buffer = new byte[8192];
                int total = 0;
                byte[] terminator = Encoding.ASCII.GetBytes("\r\n\r\n");
                while (total < buffer.Length)
                {
                    int read = stream.Read(buffer, total, buffer.Length - total);
                    if (read <= 0) break;
                    total += read;
                    if (IndexOf(buffer, total, terminator) >= 0) break;
                }

                int headerEnd = IndexOf(buffer, total, terminator);
                if (headerEnd < 0) return;
                string header = Encoding.ASCII.GetString(buffer, 0, headerEnd);
                string[] lines = header.Replace("\r", "").Split('\n');
                if (lines.Length == 0) return;
                string[] parts = lines[0].Split(' ');
                if (parts.Length < 2) return;

                string method = parts[0];
                string path = parts[1];
                int q = path.IndexOf('?');
                if (q >= 0) path = path.Substring(0, q);

                int contentLength = 0;
                for (int i = 0; i < lines.Length; i++)
                {
                    if (lines[i].StartsWith("Content-Length:"))
                    {
                        int.TryParse(lines[i].Substring("Content-Length:".Length).Trim(), out contentLength);
                    }
                }

                byte[] requestBody = null;
                if (contentLength > 0)
                {
                    int bodyStart = headerEnd + 4;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        int already = total - bodyStart;
                        if (already > 0)
                        {
                            int copy = Math.Min(already, contentLength);
                            ms.Write(buffer, bodyStart, copy);
                        }
                        while (ms.Length < contentLength)
                        {
                            int read = stream.Read(buffer, 0, buffer.Length);
                            if (read <= 0) break;
                            ms.Write(buffer, 0, read);
                        }
                        requestBody = ms.ToArray();
                    }
                }

                // 直接写入已保存的路径（保存按钮使用，不再弹窗）
                // 请求体为纯文本：第一行是目标路径，剩余部分是文件内容。
                // 相比 JSON，避免大文件在 JavaScriptSerializer 反序列化时卡顿。
                if (path == "/__ec_write_file" && method == "POST")
                {
                    string requestText = requestBody == null ? "" : Encoding.UTF8.GetString(requestBody);
                    string targetPath = "";
                    string fileContent = "";
                    int sep = requestText.IndexOf('\n');
                    if (sep >= 0)
                    {
                        targetPath = requestText.Substring(0, sep);
                        fileContent = requestText.Substring(sep + 1);
                    }
                    bool ok = false;
                    if (!string.IsNullOrEmpty(targetPath))
                    {
                        try
                        {
                            File.WriteAllText(targetPath, fileContent ?? "", Encoding.UTF8);
                            ok = true;
                        }
                        catch
                        {
                        }
                    }
                    WriteResponse(stream, "200 OK", "application/json; charset=utf-8", Encoding.UTF8.GetBytes(ok ? "{\"ok\":true}" : "{\"ok\":false}"));
                    return;
                }

                // 从磁盘读取文件内容（重新加载文件使用）
                // 请求体为纯文本：目标路径。
                if (path == "/__ec_read_file" && method == "POST")
                {
                    string targetPath = requestBody == null ? "" : Encoding.UTF8.GetString(requestBody).Trim();
                    string text = "";
                    bool ok = false;
                    if (!string.IsNullOrEmpty(targetPath))
                    {
                        try
                        {
                            if (File.Exists(targetPath))
                            {
                                text = File.ReadAllText(targetPath, Encoding.UTF8);
                                ok = true;
                            }
                        }
                        catch
                        {
                        }
                    }
                    string json = ok
                        ? "{\"ok\":true,\"path\":" + JsonEscape(targetPath) + ",\"text\":" + JsonEscape(text) + "}"
                        : "{\"ok\":false}";
                    WriteResponse(stream, "200 OK", "application/json; charset=utf-8", Encoding.UTF8.GetBytes(json));
                    return;
                }

                // 原生保存剧本：弹出 Windows 保存对话框并写盘
                // 请求体为纯文本：第一行是建议文件名，剩余部分是文件内容。
                if (path == "/__ec_save_file" && method == "POST")
                {
                    string requestText = requestBody == null ? "" : Encoding.UTF8.GetString(requestBody);
                    string suggestedName = "script.txt";
                    string fileContent = "";
                    int sep = requestText.IndexOf('\n');
                    if (sep >= 0)
                    {
                        suggestedName = requestText.Substring(0, sep);
                        fileContent = requestText.Substring(sep + 1);
                    }
                    if (string.IsNullOrEmpty(suggestedName)) suggestedName = "script.txt";
                    WriteResponse(stream, "200 OK", "application/json; charset=utf-8", Encoding.UTF8.GetBytes(SaveFileDialogWithContent(suggestedName, fileContent)));
                    return;
                }

                // 原生文件选择：返回 register.json 的完整路径和内容
                if (path == "/__ec_open_register" && method == "POST")
                {
                    WriteResponse(stream, "200 OK", "application/json; charset=utf-8", Encoding.UTF8.GetBytes(OpenRegisterDialog()));
                    return;
                }

                // 从磁盘重新读取当前保存的 register.json
                if (path == "/__ec_reload_register" && method == "POST")
                {
                    WriteResponse(stream, "200 OK", "application/json; charset=utf-8", Encoding.UTF8.GetBytes(ReloadRegisterFromDisk()));
                    return;
                }

                // 本地设置接口：用于跨启动记住用户选择的 register.json
                if (path == "/__ec_settings")
                {
                    byte[] responseBody;
                    string responseStatus = "200 OK";
                    if (method == "POST" || method == "PUT")
                    {
                        string json = requestBody == null ? "{}" : Encoding.UTF8.GetString(requestBody);
                        WriteSettingsFile(json);
                        responseBody = Encoding.UTF8.GetBytes("{\"ok\":true}");
                    }
                    else
                    {
                        responseBody = Encoding.UTF8.GetBytes(ReadSettingsFile());
                    }
                    WriteResponse(stream, responseStatus, "application/json; charset=utf-8", responseBody);
                    return;
                }

                if (path == "/") path = "/index.html";

                byte[] body = null;
                string contentType = "application/octet-stream";
                if (AssetCache.TryGetValue(path, out body))
                {
                    contentType = GetContentType(path);
                }
                else
                {
                    body = Encoding.UTF8.GetBytes("404 Not Found");
                    contentType = "text/plain; charset=utf-8";
                }

                string status = "200 OK";
                if (path != "/index.html" && !AssetCache.ContainsKey(path))
                {
                    status = "404 Not Found";
                }

                WriteResponse(stream, status, contentType, body);
            }
        }
        catch
        {
        }
    }

    private static void WriteResponse(NetworkStream stream, string status, string contentType, byte[] body)
    {
        StringBuilder sb = new StringBuilder();
        sb.Append("HTTP/1.1 ").Append(status).Append("\r\n");
        sb.Append("Content-Type: ").Append(contentType).Append("\r\n");
        sb.Append("Content-Length: ").Append(body.Length).Append("\r\n");
        sb.Append("Cache-Control: no-cache\r\n");
        sb.Append("Connection: close\r\n\r\n");
        byte[] headerBytes = Encoding.ASCII.GetBytes(sb.ToString());
        stream.Write(headerBytes, 0, headerBytes.Length);
        stream.Write(body, 0, body.Length);
    }

    private static string GetContentType(string path)
    {
        int dot = path.LastIndexOf('.');
        if (dot >= 0)
        {
            string ext = path.Substring(dot).ToLowerInvariant();
            string mime;
            if (MimeMap.TryGetValue(ext, out mime)) return mime;
        }
        return "application/octet-stream";
    }

    private static int IndexOf(byte[] haystack, int length, byte[] needle)
    {
        if (needle.Length == 0) return 0;
        for (int i = 0; i <= length - needle.Length; i++)
        {
            bool found = true;
            for (int j = 0; j < needle.Length; j++)
            {
                if (haystack[i + j] != needle[j])
                {
                    found = false;
                    break;
                }
            }
            if (found) return i;
        }
        return -1;
    }
}
'@

$template = $template.Replace('__ASSET_MAP__', $mapText)
Set-Content -Path $generated -Value $template -Encoding UTF8

# 4) Compile
if (Test-Path $exePath) { Remove-Item $exePath -Force }
$args = New-Object System.Collections.Generic.List[string]
$args.Add('/nologo')
$args.Add('/target:exe')
$args.Add('/optimize+')
$args.Add("/out:$exePath")
$args.Add('/reference:System.Windows.Forms.dll')
$args.Add('/reference:System.Drawing.dll')
$args.Add('/reference:System.Web.Extensions.dll')
foreach ($ra in $resourceArgs) { $args.Add($ra) }
$args.Add($generated)

Write-Host "Compiling $exePath ..."
& $csc @args
if ($LASTEXITCODE -ne 0) {
    throw "csc.exe failed with exit code $LASTEXITCODE"
}

Write-Host ""
Write-Host "Done: $exePath"
Write-Host "Double-click EasyChatBoxEditor.exe to launch the editor in your default browser."
